name: defichaindart
description: A dart DefiChain library for Flutter. BIP32, BIP39, P2PKH integration.
version: 2.2.1+1
homepage: https://github.com/DeFiCh-WalletApp/DeFiChain-dart

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  bech32: ^0.2.0
  bip32_defichain: ^2.0.0
  pointycastle: ^2.0.1
  hex: ^0.2.0
  bs58check_dart: ^2.0.0+1
  meta: ^1.2.4
  crypto: ^3.0.0
  
dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0
