name: defichaindart
description: A dart DefiChain library for Flutter. BIP32, BIP39, P2PKH integration.
version: 3.8.0-prerelease.12
homepage: https://github.com/DeFiCh-WalletApp/DeFiChain-dart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  defichain_bech32: ^0.1.0
  bip32_defichain: ^3.0.1+1
  pointycastle: ^3.3.4
  hex: ^0.2.0
  bs58check: ^1.0.2
  meta: ^1.3.0
  crypto: ^3.0.1
  collection: ^1.15.0
  convert: ^3.0.1

dev_dependencies:
  test: ^1.0.0
  pedantic: ^1.9.0
  _fe_analyzer_shared: ^22.0.0
